# Conda 环境描述，Azure ML 会据此在基础镜像上安装额外依赖
name: qwen-vl-lora-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - pip:
    - accelerate>=0.28.0
    - bitsandbytes>=0.43.0
    - datasets>=2.18.0
    - peft>=0.11.0
    - pillow>=10.2.0
    - sentencepiece>=0.2.0
    - timm>=0.9.12
    - torch>=2.3.0
    - torchvision>=0.18.0
    - transformers>=4.39.0
    - trl>=0.8.6
    - wandb>=0.16.0
